// Static list of all available tracks.
// gradient: [topLeft, bottomRight] hex colors used by the tile background.
// palette: [bloom1, bloom2] hex colors used by the ambient full-screen background.
export const LIBRARY = [
  { id: 'rain-light',      label: 'Rain (light)',     gradient: ['#1e3a5f', '#0d1117'], palette: ['#2a4d6e', '#1a3a4f'], file: 'audio/rain-light.m4a' },
  { id: 'rain-heavy',      label: 'Rain (heavy)',     gradient: ['#1e2a4f', '#0d1117'], palette: ['#1f3a52', '#3a3a5a'], file: 'audio/rain-heavy.m4a' },
  { id: 'thunder',         label: 'Thunderstorm',     gradient: ['#2e1a3a', '#0d1117'], palette: ['#2e2a4a', '#1a1a2e'], file: 'audio/thunder.m4a' },
  { id: 'ocean',           label: 'Ocean waves',      gradient: ['#1a2e3a', '#0d1117'], palette: ['#1a4a5e', '#0a2e3a'], file: 'audio/ocean.m4a' },
  { id: 'forest',          label: 'Forest',           gradient: ['#1a3a2e', '#0d1117'], palette: ['#1f4a35', '#3a4a1a'], file: 'audio/forest.m4a' },
  { id: 'mountain-breeze', label: 'Mountain breeze',  gradient: ['#1a2a3a', '#0d1117'], palette: ['#2a3a4f', '#3a3f4a'], file: 'audio/mountain-breeze.m4a' },
  { id: 'river',           label: 'River',            gradient: ['#1e3a3a', '#0d1117'], palette: ['#1f4a4a', '#1a3a3a'], file: 'audio/river.m4a' },
  { id: 'fireplace',       label: 'Fireplace',        gradient: ['#3a2e1a', '#0d1117'], palette: ['#5a2e1a', '#3a1a0d'], file: 'audio/fireplace.m4a' },
  { id: 'crickets',        label: 'Night crickets',   gradient: ['#2a2a1a', '#0d1117'], palette: ['#2a3a1a', '#3a3a2a'], file: 'audio/crickets.m4a' },
  { id: 'brown-noise',     label: 'Brown noise',      gradient: ['#3a2a2a', '#0d1117'], palette: ['#2a1a1a', '#1a1a1a'], file: 'audio/brown-noise.m4a' },
  { id: 'pink-noise',      label: 'Pink noise',       gradient: ['#3a2a3a', '#0d1117'], palette: ['#3a2a3a', '#2a1a2a'], file: 'audio/pink-noise.m4a' },
  { id: 'white-noise',     label: 'White noise',      gradient: ['#2a2a2a', '#0d1117'], palette: ['#2a2a3a', '#1a1a2a'], file: 'audio/white-noise.m4a' },
  { id: 'fan',             label: 'Fan / AC hum',     gradient: ['#1a1a1a', '#0d1117'], palette: ['#2a2a2a', '#1a1a1a'], file: 'audio/fan.m4a' },
  { id: 'cafe',            label: 'Coffee shop',      gradient: ['#3a2a1f', '#0d1117'], palette: ['#4a3220', '#2a1f15'], file: 'audio/cafe.m4a' },
  { id: 'train-cabin',     label: 'Train cabin',      gradient: ['#2a2a3f', '#0d1117'], palette: ['#2e2e4a', '#1a1a2a'], file: 'audio/train-cabin.m4a' },
  { id: 'library',         label: 'Library',          gradient: ['#3a2a1a', '#0d1117'], palette: ['#3a2a1a', '#5a2e1a'], file: 'audio/library.m4a' },
  { id: 'waterfall',       label: 'Waterfall',        gradient: ['#1f3a4a', '#0d1117'], palette: ['#1f3a4a', '#0a2e3a'], file: 'audio/waterfall.m4a' },
  { id: 'blizzard',        label: 'Blizzard',         gradient: ['#2a3a4a', '#0d1117'], palette: ['#2a3a4a', '#3a3f4a'], file: 'audio/blizzard.m4a' },
  { id: 'dryer',           label: 'Dryer',            gradient: ['#2a2620', '#0d1117'], palette: ['#2a2620', '#1a1a1a'], file: 'audio/dryer.m4a' },
  { id: 'airplane',        label: 'Airplane cabin',   gradient: ['#1f2a3a', '#0d1117'], palette: ['#243246', '#1a1a2a'], file: 'audio/airplane.m4a' },
  { id: 'rainforest',      label: 'Rainforest',       gradient: ['#1a3a2a', '#0d1117'], palette: ['#1a4a32', '#3a4a1a'], file: 'audio/rainforest.m4a' },
  { id: 'cave',            label: 'Cave',             gradient: ['#2a1f1f', '#0d1117'], palette: ['#3a1f1a', '#1a1a1a'], file: 'audio/cave.m4a' },
  { id: 'whale',           label: 'Whale song',       gradient: ['#1a2a4f', '#0d1117'], palette: ['#1a2e5e', '#0a1a3a'], file: 'audio/whale.m4a' },
  { id: 'meadow',          label: 'Meadow',           gradient: ['#2a3a1a', '#0d1117'], palette: ['#3a4a1a', '#1a3a2a'], file: 'audio/meadow.m4a' },
  { id: 'city-night',      label: 'City at night',    gradient: ['#2a2a3a', '#0d1117'], palette: ['#3a2a4a', '#1a2a3a'], file: 'audio/city-night.m4a' },
  { id: 'cat-purr',        label: 'Cat purring',      gradient: ['#3a2a2a', '#0d1117'], palette: ['#3a2a2a', '#2a1f1f'], file: 'audio/cat-purr.m4a', image: 'assets/cat-purr-tile.jpg' },
  { id: 'night-rain-window', label: 'Rain on window', gradient: ['#1a2a3a', '#0d1117'], palette: ['#1f3a52', '#1a2a3a'], file: 'audio/night-rain-window.m4a' },
  { id: 'night-forest',    label: 'Forest at night',  gradient: ['#1a2a1f', '#0d1117'], palette: ['#1a2e1f', '#0a1a0d'], file: 'audio/night-forest.m4a' },
  { id: 'mountain-stream', label: 'Mountain stream',  gradient: ['#1f3a4a', '#0d1117'], palette: ['#1a3a4a', '#0d2a3a'], file: 'audio/mountain-stream.m4a' },
  { id: 'night-wind-pines',label: 'Wind in pines',    gradient: ['#1a2a2e', '#0d1117'], palette: ['#1f2e3a', '#1a2a2e'], file: 'audio/night-wind-pines.m4a' },
  { id: 'alpine-meadow',   label: 'Alpine meadow',    gradient: ['#1f3a2e', '#0d1117'], palette: ['#2a4a35', '#1f3a3a'], file: 'audio/alpine-meadow.m4a' },
  { id: 'bamboo-forest',   label: 'Bamboo forest',    gradient: ['#1a2e1a', '#0d1117'], palette: ['#1f3a2a', '#1a2e1f'], file: 'audio/bamboo-forest.m4a' },
  { id: 'autumn-forest',   label: 'Autumn forest',    gradient: ['#3a2a1a', '#0d1117'], palette: ['#3a3a1a', '#2e2a1a'], file: 'audio/autumn-forest.m4a' },
  { id: 'forest-rain',     label: 'Rain on leaves',   gradient: ['#1a2e2a', '#0d1117'], palette: ['#1f3a3a', '#1a2e2a'], file: 'audio/forest-rain.m4a' },
  { id: 'night-owls',      label: 'Owls at night',    gradient: ['#1a1f2e', '#0d1117'], palette: ['#1a2a3a', '#0d1a2a'], file: 'audio/night-owls.m4a' },
  { id: 'night-pond',      label: 'Pond at night',    gradient: ['#1f2a2e', '#0d1117'], palette: ['#1a3a3a', '#1f2a2e'], file: 'audio/night-pond.m4a' },
  { id: 'city-rain',       label: 'City rain',        gradient: ['#1f2a3a', '#0d1117'], palette: ['#2a3a4a', '#1a2a3a'], file: 'audio/city-rain.m4a' },
  { id: 'subway-station',  label: 'Subway',           gradient: ['#2a2a2a', '#0d1117'], palette: ['#2a2a3a', '#1a1a2a'], file: 'audio/subway-station.m4a' },
  { id: 'harbor-fog',      label: 'Harbor foghorn',   gradient: ['#1f2a3a', '#0d1117'], palette: ['#1a2e4a', '#1f2a3a'], file: 'audio/harbor-fog.m4a' },
  { id: 'rooftop-night',   label: 'City rooftop',     gradient: ['#2a2a3a', '#0d1117'], palette: ['#2a3a4a', '#1a2a3a'], file: 'audio/rooftop-night.m4a' },
  { id: 'rain-tent',       label: 'Rain on tent',     gradient: ['#1f2a2a', '#0d1117'], palette: ['#1f3a3a', '#1a2a2a'], file: 'audio/rain-tent.m4a' },
  { id: 'campfire-night',  label: 'Campfire night',   gradient: ['#3a2a1f', '#0d1117'], palette: ['#4a2e1a', '#2a1a0d'], file: 'audio/campfire-night.m4a' },
  { id: 'cabin-rain',      label: 'Cabin rain',       gradient: ['#2a2a1f', '#0d1117'], palette: ['#3a2a1f', '#1f1a0d'], file: 'audio/cabin-rain.m4a' },
  { id: 'wolf-howl-distant',label: 'Distant wolves',  gradient: ['#1f2a2e', '#0d1117'], palette: ['#1f2a3a', '#1a1a2a'], file: 'audio/wolf-howl-distant.m4a' },
];

export function trackById(id) {
  return LIBRARY.find(t => t.id === id) || null;
}
